Vagrant.require_plugin('vagrant-hostmanager')

domain = 'dell.com'

# Define the Glance cluster
nodes = [
  { :hostname => 'glance1', :ip => '10.125.0.12', :box => 'ubuntu1204-chef'},
  { :hostname => 'glance2', :ip => '10.125.0.13', :box => 'ubuntu1204-chef'},
  { :hostname => 'glance3', :ip => '10.125.0.14', :box => 'ubuntu1204-chef'}
]


VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  nodes.each do |node|
       config.vm.define node[:hostname] do |node_config|
       # configure the box, hostname and networking 
       node_config.vm.box = node[:box]
       node_config.vm.hostname = node[:hostname] + '.' + domain
       node_config.vm.network :private_network, ip: node[:ip]

       node_config.vm.provision :chef_client do |chef|
          chef.chef_server_url = 'https://10.125.0.10'
          chef.validation_key_path = "chef-validator.pem"
          chef.add_recipe "apt"
          chef.add_recipe "mysql::client" 
          chef.add_recipe "openstack-common"
          chef.add_recipe "openstack-image::registry"
          chef.add_recipe "openstack-image::api"
          chef.add_recipe "openstack-image::identity_registration"
       end
  end
 end
end
